version: "3.7"
services:
    # Setup node container server marvel api#
    server:
        build: 
            context: ./server
            args:
                - NODE_ENV=development
        command: npm start
        environment:
            - SERVER_PORT=${SERVER_PORT}
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
        expose:
            - ${SERVER_PORT}
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
    ## Setup front container
    client:
        build: 
            context: ./client
            target: 'develop-stage'
        environment:
            - APP_PORT=${APP_PORT}
            - VUE_APP_SERVER_PATH=${VUE_APP_SERVER_PATH}
            - CHOKIDAR_USEPOLLING=true
        expose:
            - ${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
        volumes: 
            - ./client/src:/srv/app/client/src
            - ./client/public:/srv/app/client/public
        links:
            - server
        command: /bin/sh -c "yarn serve"