version: "3.7"
services:
    # Setup node container server marvel api#
    server:
        build: 
            context: ./server
            args:
                - NODE_ENV=development
        command: npm run dev
        environment:
            - SERVER_PORT=${SERVER_PORT}
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
        expose:
            - ${SERVER_PORT}
        volumes:
            - ./server:/opt/node_app/
            - ./server/package.json:/opt/node_app/package.json
            - ./server/package-lock.json:/opt/node_app/package-lock.json
            - notused:/opt/node_app/node_modules
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
    ## Setup front container
    client:
        build: 
            context: ./client
            target: 'develop-stage'
        environment:
            - APP_PORT=${APP_PORT}
            - VUE_APP_SERVER_PATH=${VUE_APP_SERVER_PATH}
            - CHOKIDAR_USEPOLLING=true
        expose:
            - ${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
        volumes: 
            - ./client/src:/app/src/
            - /app/node_modules
        links:
            - server
        command: yarn serve
volumes:
    notused: