version: '3'
# a stack-file version of this for running in Swarm services
services:
  server:
    # reminder, don't use latest tag in production, use versions created by CI/CD
    image: develord09/server:latest
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
    command: node index.js
  client:
      image: develord09/client:latest
      environment:
          - CHOKIDAR_USEPOLLING=true
      restart: unless-stopped
      expose:
          - ${APP_PORT_PROD}
      ports:
          - ${APP_PORT_PROD}:${APP_PORT_PROD}
      links:
          - server